FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy parent pom first
COPY pom.xml .
COPY auth-service/pom.xml auth-service/
COPY common/pom.xml common/
COPY employee-service/pom.xml employee-service/
COPY patient-service/pom.xml patient-service/

# Copy source code
COPY auth-service/src auth-service/src
COPY common/src common/src

# Build the application
RUN mvn clean package -pl auth-service -am -DskipTests

FROM eclipse-temurin:17-jdk-alpine
RUN apk add --no-cache curl

WORKDIR /app
COPY --from=builder /app/auth-service/target/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java","-jar","app.jar"]