pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven'
        nodejs 'NodeJS18'
    }

    environment {
        JAVA_HOME = tool('JDK17')
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('hospital-management-system') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        //stage('Run Backend Tests') {
            //steps {
                //dir('hospital-management-system') {
                    //sh 'mvn test'
                //}
            //}
        //}

        stage('Install Frontend Dependencies') {
            steps {
                dir('Front/front/employee-front') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('Front/front/employee-front') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Run Docker Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Check Running Containers') {
            steps {
                sh 'docker ps'
            }
        }
    }

    post {
        always {
            echo "🧹 Cleaning up Docker containers..."
            sh 'docker compose down'
        }
        success {
            echo '✅ Build and deployment succeeded!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}
