# ===============================
# Stage 1 - Build from parent POM
# ===============================
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app
COPY . .

# Build only the patient-service module without tests
RUN mvn clean package -pl patient-service -am -DskipTests

# ===============================
# Stage 2 - Runtime
# ===============================
FROM eclipse-temurin:17-jdk-alpine
RUN apk add --no-cache curl

WORKDIR /app

# Copy the fat jar from the build stage
COPY --from=builder /app/patient-service/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
