# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --silent
COPY . .
RUN npm run build -- --configuration production

# Production stage  
FROM nginx:1.25-alpine
COPY --from=build /app/dist/employee-front /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]